make BOOST=-DWITH_BOOST LOG4CXX=-DWITH_LOG4CXX FILECONF=-DWITH_FILECONF MONGODB=-DWITH_MONGODB MYSQL=-DWITH_MYSQL OPENCV=-DWITH_OPENCV CV=-DSUPPORT_CV2 OUTPUT_TARGET=-DSHARED_LIB PY=-DSUPPORT_PYTHON3
